version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - './api:/app'
      - '/app/node_modules'
    networks:
      - iab330
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    hostname: client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    networks:
      - iab330
networks:
  iab330:
     external: true